dbt_learning:
  outputs:
    dev:
      type: duckdb
      path: './database/dbt_learning_dev.duckdb'
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: main

    prod:
      type: duckdb
      path: './database/dbt_learning_prod.duckdb'
      schema: main
      threads: 8
      keepalives_idle: 0
      search_path: main

    test:
      type: duckdb
      path: ':memory:'
      schema: main
      threads: 2
      keepalives_idle: 0
      search_path: main

  target: dev
