version: 2

snapshots:
    - name: customers_snapshot
      description: "Snapshot historique des données clients pour tracer l'évolution des métriques"
      columns:
          - name: customer_id
            description: "Identifiant unique du client"
          - name: first_name
            description: "Prénom du client"
          - name: last_name
            description: "Nom de famille du client"
          - name: email
            description: "Adresse email du client"
          - name: registration_date
            description: "Date d'inscription du client"
          - name: customer_segment
            description: "Segment client au moment du snapshot"
          - name: customer_status
            description: "Statut client au moment du snapshot"
          - name: total_orders
            description: "Nombre total de commandes au moment du snapshot"
          - name: total_spent
            description: "Montant total dépensé au moment du snapshot"
          - name: avg_order_value
            description: "Valeur moyenne des commandes au moment du snapshot"
          - name: delivery_success_rate
            description: "Taux de réussite des livraisons au moment du snapshot"
          - name: dbt_updated_at
            description: "Timestamp de mise à jour des données source"
          - name: dbt_scd_id
            description: "Identifiant unique du snapshot (généré par DBT)"
          - name: dbt_updated_at
            description: "Timestamp de création du snapshot"
          - name: dbt_valid_from
            description: "Date de début de validité de cet enregistrement"
          - name: dbt_valid_to
            description: "Date de fin de validité (null si actuel)"
