name: DBT Scheduled Run

on:
    schedule:
        # Exécution quotidienne à 6h du matin UTC
        - cron: "0 6 * * *"
    workflow_dispatch: # Permet l'exécution manuelle

env:
    DBT_PROFILES_DIR: ${{ github.workspace }}
    DBT_PROJECT_DIR: ${{ github.workspace }}

jobs:
    scheduled-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v2

            - name: Set up Python
              run: uv python install 3.11

            - name: Install dependencies
              run: |
                  uv sync
                  uv sync --extra dev

            - name: Install DBT dependencies
              run: uv run dbt deps

            - name: Generate sample data
              run: uv run python scripts/generate_sample_data.py

            - name: DBT Run (Production)
              run: uv run dbt run --target prod

            - name: DBT Test (Production)
              run: uv run dbt test --target prod

            - name: Run snapshots
              run: uv run dbt snapshot --target prod

            - name: Send notification on failure
              if: failure()
              uses: 8398a7/action-slack@v3
              with:
                  status: failure
                  channel: "#data-alerts"
                  webhook_url: ${{ secrets.SLACK_WEBHOOK }}
