name: DBT Scheduled Run

on:
    schedule:
        # Exécution quotidienne à 6h du matin UTC
        - cron: "0 6 * * *"
    workflow_dispatch: # Permet l'exécution manuelle

env:
    DBT_PROFILES_DIR: ${{ github.workspace }}
    DBT_PROJECT_DIR: ${{ github.workspace }}

jobs:
    scheduled-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3

            - name: Set up Python
              run: uv python install 3.13

            - name: Install dependencies
              run: |
                  uv sync --locked --all-extras --dev

            - name: Install DBT dependencies
              run: uv run dbt deps

            - name: Create database directory
              run: mkdir -p database

            - name: Generate sample data
              run: uv run python scripts/generate_sample_data.py

            - name: DBT Run (Production)
              run: uv run dbt run --target prod

            - name: DBT Test (Production)
              run: uv run dbt test --target prod

            - name: Run snapshots
              run: uv run dbt snapshot --target prod
